#!/bin/bash
read oldrev newrev refname

# This can be generated in the admin page, make sure to enable the WS.
REDMINE_KEY='yourrepositorymanagementwskeyhere'

# Quickly do a lookup of our working directory and see which project it belongs to.
PROJECT_ID=$(mysql -r -u redmineuser -predminepassword redminedb -e "select project_id from repositories where url = '$PWD';")

# Do the update.
curl -s http://yourredmineurl/sys/fetch_changesets?key=$REDMINE_KEY&id=$PROJECT_ID
